### PR TITLE
Fixed issues in DriveUserDataAccess (+schema and DriveResource)

### LINKED ISSUE #99: Fix Issue with DriveUserDataAccess
Change method inside addDriveUser to execute instead of insert to prevent execution issues (insert expects unique id, which there is none).

Add rated column to database scheme

### PR DESCRIPTION
**Pull request by Hackerlacka**
Replaced insert with execute in addDriveUser (since insert expects one unique id however DriveUser's uniqueness is given from drive_id and user_id together).

Added missing boolean rated column to the database table (through schema)

Updated methods missing the boolean rated (in DriveResource and DriveUserDataAccess).

Fixes #99

### CODE REVIEW

File: src/main/java/se/lth/base/server/data/DriveUserDataAccess.java [hunk 1]
```diff
@@ -34,28 +34,28 @@ public DriveUser map(ResultSet resultSet) throws SQLException {
...
     	return new DriveUser(driveId, userId, start, stop, driver, accepted, !HAS_RATED);
     }
-    
-    public DriveUser updateDriveUser(int driveId, int userId, String start, String stop, boolean driver, boolean accepted) {
-    	execute("UPDATE drive_user SET start = ?, stop = ?, is_driver = ?, accepted = ? WHERE drive_id = ? AND user_id = ?",
-                start, stop, driver, accepted, driveId, userId);
+
+    public DriveUser updateDriveUser(int driveId, int userId, String start, String stop, boolean driver, boolean accepted, boolean rated) {
+        execute("UPDATE drive_user SET start = ?, stop = ?, is_driver = ?, accepted = ?, rated = ?, WHERE drive_id = ? AND user_id = ?",
+                start, stop, driver, accepted, driveId, userId, rated);
```
Comment (McPoppe) [inline src/main/java/se/lth/base/server/data/DriveUserDataAccess.java]: Wrong order on the parameters, rated should be third last
